CREATE TABLE [dbo].[Board]
(
	[Id] UNIQUEIDENTIFIER NOT NULL  DEFAULT NEWID(), 
    [UserName] NVARCHAR(256) NOT NULL, 
    [BoardName] NVARCHAR(256) NOT NULL, 
    CONSTRAINT [PK_Board] PRIMARY KEY ([Id]) 
)
